### ISSUE TITLE
Clarify readme

### ISSUE THREAD

**Issue by jcoyne** [fcrepo4-labs/fcrepo-webapp-plus#14]
> This project builds custom-configured fcrepo4 webapp war files that include extra dependencies and configuration options

Does this mean it builds multiple warfiles when I do `mvn install` or it can build different warfiles based on the flags passed? I suspect it's the later, but the phrasing is unclear. 

If indeed it only builds a single file I'd suggest:
> This project builds a custom-configured fcrepo4 webapp war file that include extra dependencies and configuration options

**Comment by awoods** [comment]
PR accepted.

**Comment by jcoyne** [comment]
Cant write a PR because I don't understand what it's supposed to do. I wrote a question in my ticket that needs answering.

**Comment by awoods** [comment]
https://github.com/fcrepo4-labs/fcrepo-webapp-plus/commit/eccc558e5245ea9dd48f59e60ef9d249871fbe78
